### ISSUE TITLE
Adding a remap bucket type

### ISSUE THREAD

**Issue by cholcombe973** [domodwyer/anchorhash#10]
Imagine a scenario where you have 4 servers:
```
server-a
server-b
server-c
server-d
```
and all of them are servicing 25% of the load using anchorhash. `server-d` now dies and load is being redistributed to the other 3 servers. Some of the new objects that are being written to those 3 servers will need to be redistributed once `server-d` comes back. How does one discover which objects need to be rewritten when the 4th server returns to service? 

1. The 1st way I can think of is just to rehash every single object in the cluster. ( expensive )
2. The 2nd way would be if anchor had some way of telling me which objects are being redirected and saving those somewhere as needing to be rebuilt. 
3. The 3rd way could be push this to the client and if they happen to write an object that is now going to the wrong server then it gets rebuilt. 

There's probably other ways but I think the 2nd way could be the easiest if a small modification was made to anchor.

**Comment by domodwyer** [comment]
Hey @cholcombe973 

AnchorHash doesn't store the keys internally, so it has no way of reporting what has moved where in the situation you describe. The keys themselves are hashed and then mapped to a bucket, and the only state maintained are the buckets.

The only way to know what has moved is to know what keys were mapped to `server-d`, which means keeping a map of keys -> resources, which is prohibitively expensive if you're hashing session IDs or ip:port tuples at a rate of thousands-per-second. Most applications don't care about a session ID after a request, and definitely don't want to keep it in memory!

If your application needs to figure out what keys have been remapped (and you have a low number of keys / are happy to use the memory), I suggest wrapping the `AnchorHash` with a higher-level type that _also_ maintains a map of `resource -> [keys]`. When you call `AnchorHash::remove_resource()` you then lookup all the keys that mapped to `server-d`, rehash them, and update the mapping as necessary. This effectively means that AnchorHash is used to build the mappings, and your application caches the results.

This is a long way of saying I think it has to be option 3 to remain a flexible/reusable component in systems that don't/can't store the keys - I hope I explained why well enough!
