### ISSUE TITLE
Inconsistent hashes on different computers?

### ISSUE THREAD

**Issue by praveenperera** [domodwyer/anchorhash#17]
If one machine has the SIMD instructions and another has to fall back to FNV? Will those not end up hashing to different buckets?

And is FNV consistent on all machines? Could this be avoided by switching to seahash, and opting out of SIMD?

**Comment by domodwyer** [comment]
Hey Praveen!

> If one machine has the SIMD instructions and another has to fall back to FNV? Will those not end up hashing to different buckets?

Yes that's right - if you're using a mix of machines, where some doesn't provide SSE4.2 SIMD operations (perhaps a non-intel CPU, or something pre-2006) then you should disable the SIMD accelerated hash and use FNV only.

FNV hashing is deterministic, so there should be no issues across platforms (it is platform independent).

Dom

**Comment by praveenperera** [comment]
Thanks @domodwyer !
