### ISSUE TITLE
get_resource redirect

### ISSUE THREAD

**Issue by cholcombe973** [domodwyer/anchorhash#7]
First off I wanted to say I was really happy to see this open source implementation of anchorhash done with such high quality! I wrote an implementation of anchorhash while at a previous company but I was unable to get it through the open source process. 
My question revolves around the `get_resource` function of anchorhash. It returns an `Option<&R>`. What does the `None` value mean in this context? 
Would it be possible to change the `get_resource` function so that it returned whether the resource you asked it for was in the original bucket or a remapped bucket? I think this would be helpful to know.

**Comment by domodwyer** [comment]
Hey @cholcombe973, thanks for the kind words! Much appreciated :)

A `None` can be returned when the `AnchorHash` instance contains no resources - either through all of them being removed after construction, or having being constructed with no resources in the first place.

This definitely isn't clear, so I pushed #8 to add this to the docs. Thanks for pointing it out!

Dom
